### ISSUE TITLE
Adaptors references wrong WebClient Package

### ISSUE THREAD

**Issue by krono** [SeasideSt/Seaside#1037]
The `WebClient-Seaside` Package was split in 2015, and was used as such (`-Adaptor` and `-Tools-Development`) in [the Configuration](https://github.com/SeasideSt/Seaside/blob/ae955e799bb4bec8dbbbc94d770dcb0d7d4c9a02/repository/ConfigurationOfSeaside3.package/ConfigurationOfSeaside3.class/instance/baseline320adaptors..st#L26)

However, in [the Baseline](https://github.com/SeasideSt/Seaside/blob/develop/repository/BaselineOfSeaside3.package/BaselineOfSeaside3.class/instance/baselineadaptors..st#L39) an outdated variant is use.

In turn, there are now two incompatible Seaside 3.2 for Squeak.

I would prefer the version from the Configuration

**Comment by marschall** [comment]
So you're saying we should be referencing `WebClient-Seaside` instead of `WebClient-Seaside-Adaptor` in Seaside 3.2?

The 3.3 baseline references `WebClient-Seaside` https://github.com/SeasideSt/Seaside/blob/develop/repository/BaselineOfSeaside3.package/BaselineOfSeaside3.class/instance/baselineadaptors..st

**Comment by krono** [comment]
No, to the contrary.

The _Baseline_ uses `WebClient-Seaside`, but should use `WebClient-Seaside-Adatpor`. 
The _Configuration_ already does the right thing

**Comment by krono** [comment]
thanks!
