### ISSUE TITLE
Should JSON group be loaded by default?

### ISSUE THREAD

**Issue by jecisc** [SeasideSt/Seaside#1085]
I have the impression that most users do not need the JSON group for a basic Seaside application so I wonder if it should be in the default group?

Maybe I am missing something that make it interesting for basic Seaside usage?

**Comment by jbrichau** [comment]
The 'default' Metacello group does not mean it's loaded by default; it's loaded when you do not specify any specific group.

It's in the default group because that's what Seaside newcomers are always loading. Most users also do not need the 'Welcome' group or maybe even the 'Email' group, and those users can avoid loading those parts by specifying exactly those groups they want, starting with 'Core'.

We should keep the default group loading as much to demonstrate Seaside as possible to newcomers. Those who want to filter things out, can do so.

**Comment by jecisc** [comment]
Ok :)

**Comment by jbrichau** [comment]
I'm just busy writing some doc on the groups ;)
