### ISSUE TITLE
Add WAAnchorTag>>openInNewTab

### ISSUE THREAD

**Issue by jecisc** [SeasideSt/Seaside#1124]
I think some syntactic sugar "openInNewTab" would be interesting in anchors.

**Comment by marschall** [comment]
We had this in the past and intentionally removed it because it goes against web development best practices, letting the user decide how he wants to open a link.

**Comment by jecisc** [comment]
I think that in some cases it can be useful because if you have a page with a fork the user need to fill and add a link where the user can get more informations, in any case you do not want to open the link in the current page, else it would discard everything the user already filled. 

But if you think Seaside should really not implement it I’m fine with it. It’s not hard to find how to do it in case we really need it.

**Comment by marschall** [comment]
I'm kinda split. On one hand having it encourages its use on the other hand if people are using it anyway it makes sense to add it.

Do you use it in your applications?

**Comment by jbrichau** [comment]
I'm in favour of adding it. Basically, if you need it, you are going to implement it yourself in the same way, so it makes sense to add an abstraction for it to Seaside. Users will most often ask the developer to make certain links open new tabs instead of having them have to do it.

**Comment by jecisc** [comment]
I use it in one application. Probably in another one later. 
I can update the PR to add a warning in the comment. Not sure everyone will read it but it’s better than nothing.

**Comment by jbrichau** [comment]
There was a question and two possible solutions recently on the mailinglist: http://lists.squeakfoundation.org/pipermail/seaside/2019-February/033334.html

**Comment by jecisc** [comment]
@jbrichau I don't know if you saw that I already opened a PR for that.

**Comment by jbrichau** [comment]
@jecisc Yes, I saw it. I just pointed to the discussion, as there is another solution using a presenter (which I need to discover a bit myself what exactly that is doing though..., which is why I put it in here).

**Comment by jbrichau** [comment]
I refreshed my memory on the `popupAnchor`. We also never use that one but use the `target="_blank"`

Now, there are several meanings to the target attribute. My impression is that it would be cleaner if we can add them all instead of just this one (see https://www.w3schools.com/html/html_links.asp). We might also want to avoid using the name 'tab' as it is not guaranteed that a new tab or a new window opens.

Suggestions:
- `#targetNew for `target="_blank"`
- `#targetSame for `target="_self"`
- `#targetParent for `target="_parent"`
- `#targetTop` for `target="_top"`
This then also remains consistent if you want to use `#target:` with a named frame.

**Comment by marschall** [comment]
@jbrichau that makes sense. If I may ask, why `#targetNew` and not `#targetBlank`?
