### ISSUE TITLE
JSAjaxCallback should signal callback errors as Status Code <> 200

### ISSUE THREAD

**Issue by JoachimTuchel** [SeasideSt/Seaside#1177]
In Pharo 7 and Seaside from the Catalog Browser (How do I find out which version that actually is?), Seaside always answers Ajax callbacks with a 200 OK by default, even if the callback on the server signals and unhandled exception. The same problem exists in older versions (like the 3.2. version that ships with VA Smalltalk 9.1).

I'm attaching a little fileout to demonstrate the problem. Please see the class comment on JTSeasideAjaxTestComponent for more details

[JTSeasideAjaxProblem.st.txt](https://github.com/SeasideSt/Seaside/files/3564551/JTSeasideAjaxProblem.st.txt)

I would expect a 500 Internal Server error or some status out of the 4xx range if a callback on the server breaks. Thus you can add a js error handler (like in the attached sample which uses an onError: to alert an error). Instead, you get a 200 even if the callback fails. This does not allow for any kind of reaction on the client side...

**Comment by JoachimTuchel** [comment]
suggested fix in JSAjaxCallback>>#evaluateWithArgument:

```

evaluateWithArgument: anObject
	block isNil
		ifFalse: [ [ block valueWithPossibleArguments: (Array with: anObject) ]
				on: Error
				do: [ :ex | 
					self requestContext
						respond: [ :response | 
							response
								status: 500;
								nextPutAll: ex description ] ] ].
	self requestContext respond: [ :response | response doNotCache ]
```

**Comment by marschall** [comment]
> suggested fix in JSAjaxCallback>>#evaluateWithArgument:

That shouldn't really be necessary. That should be done by the error handler on the application. I had a quick look and it seems to be a nesting issue with exception handlers.

**Comment by JoachimTuchel** [comment]
Not sure I understand. Are you saying my suggestion is not the correct fix and the problem lies somewhere in the exception handling, or are you saying my test code misses the right (combination of) exception handler(s)? If so, what would be the correct setup of an Application?

**Comment by marschall** [comment]
> Not sure I understand. Are you saying my suggestion is not the correct fix and the problem lies somewhere in the exception handling

yes

Things should "just work" in your first comment and an HTTP 500 should be returned from the application exception handler. Somewhere in the Seaside exception handler hierarchy there is a bug and the exception handler is not called, therefore HTTP 200 in returned.

**Comment by JoachimTuchel** [comment]
I see. Thanks for clarifying!

Can you give me a hint where to start debugging so that I can help?

**Comment by jbrichau** [comment]
Sorry, very late to the party but I'm walking over some unhandled issues to see what needs to be done. Picking up this one.

I don't see this as an ajax-specific issue. If you also put a `1/0` error in the `renderContentOn:` method, you will see the same behavior: if you proceed, then the request just goes past the zero-divide error.

Also, this is how the `WADebugErrorHandler` is supposed to work imho. See `WADebugErrorHandler>>resume:`. If the exception is resumable, it will allow to resume. 

If you want to have an error 500 thrown on proceeding from the debugger, you can subclass the error handler and implement the status 500 response in the `resume:` method, for example.

I'm closing this issue, since I think this is probably an application-specific way you want to debug your actions and Seaside allows you to do that via customization. If I misinterpreted the issue, don't hesitate to comment and open it again.

**Comment by JoachimTuchel** [comment]
Hmm. This is not about the Debugger and proceeding from an Exception.
It is about the fact that an error in an Ajax callback doesn't get communicated to the Client/Browser. Or even worse (imo), it is answered with a 200 HTTP Code as if nothing happened. I think it would be good if I could react to errors on the Javascript side. 

... unless there is a way to add some error handler for Ajax Callbacks only that would catch Exceptions and give me the chance to send out a 500 or whatever... Is there any documentation or sample code I could look at?

Or what am I getting wrong? What is the right way to answer an Ajax callback with a Status code <> 200? 
How do I decide in an Error Handler if the error occured in an ajax callback?

**Comment by jbrichau** [comment]
Hi @JoachimTuchel 

I walked through the example and had the impression it was about 'not getting an error 500 when proceeding from the debugger'. 
What you describe should work as you expect it: when an error is raised in an ajax callback, the regular Seaside exception handlers kick in.

I just tested it by registering the `WAErrorHandler` instead of the `WADebugErrorHandler` for your example. When I click on the button, I get an error 500 and the alert window is shown:

![Uploading Screenshot 2021-05-15 at 18.04.26.png…]()

**Comment by JoachimTuchel** [comment]
Hi Johan,

So the WAErrorHandler did the trick ;-) 

It is now my job to find out how my own exception handler should behave in an Ajax vs. ActionCallback situation....

Thanks for clarifying.

Joachim

**Comment by jbrichau** [comment]
@JoachimTuchel Good to hear this helps you further. Though I have not experienced a situation where the error handler should behave differently between ajax and action or render callbacks.

It's slightly different in the case of ajax script callbacks though, as an error 500 handler will not send back a Js script but an html. This will always crash the jQuery handler that tries to parse the response. 

We have not have a really elegant answer to that (yet), but you can make a distinction on what to respond in your error handler by looking at `self requestContext request accept` which will either say the browser expects html or a javascript.
