### ISSUE TITLE
Improper store into indexable object when sending printString to instances of WAUrl when the codec is utf-8 on Pharo 9

### ISSUE THREAD

**Issue by gcotelli** [SeasideSt/Seaside#1278]
When sending `printString` to `WAUrl` instances generated under a context with `GRPharoUtf8Codec` the method fails with `Improper store into indexable object`

Find attached a TestCase fileout to reproduce the problem.

[WASeasideUrlComparisonUsingUtf8CodecTest.st.zip](https://github.com/SeasideSt/Seaside/files/7086523/WASeasideUrlComparisonUsingUtf8CodecTest.st.zip)

Seaside version: v3.4.5
Grease version: v1.7.3
Pharo version: Pharo9.0.0 Build information: Pharo-9.0.0+build.1534.sha.bf4a85fdfcdb57bc7cef5a4df791e1d4bd9c791c (64 Bit)

**Comment by gcotelli** [comment]
Here's the relevant stack :
```
ByteString(Object)>>error:
ByteString(Object)>>errorImproperStore
ByteString>>at:put:
LimitedWriteStream(WriteStream)>>nextPut:
LimitedWriteStream>>nextPut:
WAUrlEncoder(WATableBasedEncoder)>>nextPut:
WAPharoUrlEncoder(WAPharoEncoder)>>nextPut:
ZnUTF8Encoder>>nextPutCodePoint:toStream:
ZnUTF8Encoder(ZnCharacterEncoder)>>nextPut:toStream:
GRPharoConverterCodecStream>>nextPut:
[ :each | self nextPut: each ] in GRPharoConverterCodecStream>>nextPutAll: in Block: [ :each | self nextPut: each ]
ByteString(SequenceableCollection)>>do:
GRPharoConverterCodecStream>>nextPutAll:
WAUrl>>encodeSchemeAndAuthorityOn:
WAUrl>>encodeOn:
WAUrl>>printOn:
[:s | self printOn: s] in WAUrl(Object)>>printStringLimitedTo: in Block: [:s | self printOn: s]
String class(SequenceableCollection class)>>streamContents:limitedTo:
WAUrl(Object)>>printStringLimitedTo:using:
WAUrl(Object)>>printStringLimitedTo:
WAUrl(Object)>>printString
WASeasideUrlComparisonUsingUtf8CodecTest>>testComparison
WASeasideUrlComparisonUsingUtf8CodecTest(TestCase)>>performTest
[ super performTest ] in [
			self
				pushAll: self createHandlers
				during: [ super performTest ] ] in WASeasideUrlComparisonUsingUtf8CodecTest(WAContextTest)>>performTest in Block: [ super performTest ]
WASeasideUrlComparisonUsingUtf8CodecTest(WAContextTest)>>pushAll:during:
[
			self
				pushAll: self createHandlers
				during: [ super performTest ] ] in WASeasideUrlComparisonUsingUtf8CodecTest(WAContextTest)>>performTest in Block: [...
[ activeProcess
			psValueAt: index
			put: anObject.
		aBlock value ] in WACurrentRequestContext(DynamicVariable)>>value:during: in Block: [ activeProcess...
FullBlockClosure(BlockClosure)>>ensure:
WACurrentRequestContext(DynamicVariable)>>value:during:
WACurrentRequestContext class(DynamicVariable class)>>value:during:
```

**Comment by jbrichau** [comment]
Hi @gcotelli 

Seaside in Pharo 9 should use Grease's `GRPharoDeprecatedUtf8Codec` class for now.  If you retrieve the codec using the factory method, you will get the right class:

```Smalltalk
GRCodec forEncoding:'utf8'
```

The issue to move away from the deprecated implementation is captured in: https://github.com/SeasideSt/Seaside/issues/1239 

Once that has been solved, Seaside users in Pharo9 will be able to switch the setting in the GRPlatform class to use the Zinc UTF8 encoder rather than the deprecated TextConverter.

**Comment by gcotelli** [comment]
Thank you @jbrichau . Changing the code to retrieve the code using the factory works great!

**Comment by daniels220** [comment]
It appears this issue is back as of Pharo 10 (I'm actually using 11, but it looks like Grease treats the two the same)—`GRPharoDeprecatedUtf8Codec` only exists in Pharo 9 (`Grease-Pharo90-Core`), in Pharo 10/11 `GRCodec forEncoding: 'utf8'` returns the new `GRPharoUtf8Codec`. What's worse, this now affects writing the XML/HTML document body, not just URL encoding.
