### ISSUE TITLE
Deprecation: Symbol>>#asMutator has been deprecated. Use #asSimpleSetter instead

### ISSUE THREAD

**Issue by asarch** [SeasideSt/Seaside#1300]
How can you fix this? Squeak 5.3 for AMD64 with Seaside from the installation instructions (3.4.6).
```
Seaside Walkback
Deprecation: Symbol>>#asMutator has been deprecated. Use #asSimpleSetter instead

Debug Proceed Full Stack
Stack Trace

    thisContext
        ByteSymbol(Object)>>deprecated:
    self
        #componentName

    explanationString
        'Use #asSimpleSetter instead'

    thisContext
        ByteSymbol(Symbol)>>asMutator
    self
        #componentName

    thisContext
        WATextInputTag(WAFormInputTag)>>on:of:
    self
        a WATextInputTag

    aSelector
        #componentName
    anObject
        a WAWelcomeComponentNamePrompter

    thisContext
        [] in WAWelcomeComponentNamePrompter>>renderContentOn:
    self
        a WAWelcomeComponentNamePrompter

    html
        a WAHtmlCanvas

    thisContext
        BlockClosure>>renderOn:
    self
        [closure] in WAWelcomeComponentNamePrompter>>renderContentOn:

    aRenderer
```

**Comment by jbrichau** [comment]
It seems that in Squeak the error handler is capturing deprecation signals? Since this is just a deprecation, it should continue to work.
However, I am not using Squeak and stopped actively maintaining it. The automated builds are failing since some time.

Incidentaly, this issue is related to one of the last fixes I did specifically for Squeak. It is still open to finish but, as I said, it is just a deprecation at the moment. https://github.com/SeasideSt/Seaside/issues/1195

**Comment by tcj** [comment]
I see this delightful bit in the release notes for upcoming Squeak 6.0:

```- #asMutator is back to preserve the well-known Smalltalk legacy and improve the backwards compatibility for projects such as Seaside. However, new code should use #asSimpleSetter instead.```

So perhaps this issue can be retired...?  I am very happy Squeak made that decision.
