### ISSUE TITLE
testCORSFilterFunctionalTest is broken on github CI

### ISSUE THREAD

**Issue by jbrichau** [SeasideSt/Seaside#1362]
`testCORSFilterFunctionalTest` stopped working when moving to Ubuntu 20 on github CI.
It works fine locally, so it has been marked as an expected failure for now

**Comment by dalehenrich** [comment]
When this bug is fixed, I will want to remove the [GsDevKit_home workaround](https://github.com/GsDevKit/GsDevKit_home/tree/issue_328) by reverting back to master branch from branch issue_328

**Comment by dalehenrich** [comment]
When this bug is fixed, I will want to remove the [GsDevKit_stones workaround](https://github.com/GsDevKit/GsDevKit_stones/commit/33a600911d033f14092f9f04ee4be687dab41816) to avoid failing tests because of unexpected passes .. no need to undo GsDevKit_home workaround as GsDevKit_stones is replacing GsDevKit_home

**Comment by jbrichau** [comment]
@dalehenrich This bug is now fixed ;-)
Fixed in https://github.com/SeasideSt/Seaside/commit/61d83eb27a124ba023b6748115c7230e4cba0833
