### ISSUE TITLE
WAPharoInspector cannot evaluate (compile) expressions in Pharo 11

### ISSUE THREAD

**Issue by eMaringolo** [SeasideSt/Seaside#1372]
Every time you attempt to evaluate something in the `WAPharoInspector` you get `Error: Receiver is not same as context receiver`, this might be due to some changes in the Opal Compiler.

It can be fixed by adding a semantic scope to the compiler:

```smalltalk
WAPharoInspector>>#evaluate

    ^self object class compilerClass new
       source: input;
       context: thisContext;
       semanticScope: (OCReceiverDoItSemanticScope targetingReceiver: self object); "<-- this"
       receiver: self object;
       evaluate
```

**Comment by jbrichau** [comment]
Thanks @eMaringolo for reporting and proposing a solution. 

I'm looking into this and notice that it works without the change in Pharo12 because the `receiver:` method is essentially doing the same thing. In Pharo 11, it fails because the `context` was set to `thisContext` which actually does not make sense to me though it has been like this for over 10 years 🙄
