### ISSUE TITLE
Slow down when rendering € with Pharo 3 on Seaside 3.1

### ISSUE THREAD

**Issue by hilaire** [SeasideSt/Seaside#862]
In some situation there is a important slow down when rendering €:

This example shows the slow down:

    1500 timesRepeat: [ html text: 'hello', '€' ].

But not this one:

    1500 timesRepeat: [ html text: 'hello'; text: '€' ].

It is really a problem with custom object using the € monetary symbol. 
For example a Money symbol with a printOn: method:

    printOn: aStream
        aStream << (amount asScaledDecimal: 2) greaseString << ' ' << '€'

In this case, the insertion of the '€' string in the stream will slow down the page rendering

For some explanation of the problem read http://forum.world.st/TableReport-slow-down-tp4868925p4868931.html

**Comment by jbrichau** [comment]
Thanks for posting that.
Since the slowdown is only in the example where you concatenate the euro symbol to the string before writing it on the canvas, it’s definitely not something we can/should solve in Seaside.
I wanted to make sure if there is anything that slows down the page rendering when there are widestrings being put on the canvas, but it’s clearly not the case.
