### ISSUE TITLE
Scriptaculous scripts are still strings when the should be script objects

### ISSUE THREAD

**Issue by theseion** [SeasideSt/Seaside#863]
See this question for details: http://stackoverflow.com/questions/35121074/using-lightbox-in-seasides-wacomponent-appears-in-halos-but-the-browser-doesn/35135404?noredirect=1#comment58386441_35135404

The scriptaculous lightbox script for instance is still a string. When `WAScriptGenerator` renders the load scripts these strings will be rendered literally and thus the functions don't work. The "fix" provided in the StackOverflow answer works but is actually a work around. A real fix should change the scriptaculous methods to return script objects instead of strings.

This is reproducible within the Seaside 3.1 one-click image.

**Comment by jbrichau** [comment]
Completely missed this one. Will take a look, thx!

**Comment by jbrichau** [comment]
There was a change from Seaside 3.0 to 3.1 where scripts should always be `JSObject` (sub)instances. Therefore, the fix should be to change the `lighter` method to:


    lighter
	    ^ JSStream on: 'updateLightbox();Event.observe(window,"resize",function(){updateLightbox();});'

A Smalltalk string now always is converted to a Javascript string. The change is because of this issue: #742 but it was not well documented indeed (sorry about that).

Fixed in Scriptaculous-Components-JohanBrichau.116
