### ISSUE TITLE
Older platforms require Filetree meta data files or newer Metacello version

### ISSUE THREAD

**Issue by theseion** [SeasideSt/Seaside#935]
Travis builds for older versions fail if certain meta data files are missing. The solution is to force the use of the latest Metacello version (which is trivial with smalltalkCI). However, I’m not sure whether we can expect users of older platforms to suddenly require a newer version of Metacello. 

This will certainly hit us when we start using Iceberg fully, as Iceberg does not write meta data files. If we still want to go that way, which I think we should, we need to decide, whether we can start now and require older platforms to load a newer Metacello version, or whether we want to have a release with a clean transition (we could simply say that it will be 3.3).

If we decide to wait, then I will have to redo my PR's as they are missing meta data files.
@jbrichau @marschall please comment.

**Comment by dalehenrich** [comment]
@theseion I don't think that it is unreasonable to require older platforms to use the latest version of Metacello ... the latest version of Metacello runs on older platforms the api is backward compatible ... whether or not they are using Seaside, folks running on older platforms **should** be running with the latest version of Metacello anyway, since there are bugfixes ...

**Comment by marschall** [comment]
I agree with @dalehenrich

**Comment by jbrichau** [comment]
I agree but every time I try to use Iceberg, I get debuggers popping up all over the place which makes me wonder if we should already go for the metadataless format. At the very least, I find it difficult to trust it at this time. 

I just tried again, both the Iceberg coming in Pharo6 and also updating it to the last version... 

Do you have different experiences?

**Comment by jbrichau** [comment]
Another issue that might arise is the ports to VA and VW: can they still get reasonable source code extraction for their platform from a metadata-less repository?

**Comment by dalehenrich** [comment]
@jbrichau with or without metadata, I think that in order for VA and VW to extract source from FileTree, the developer must write an mcz file and that can still be achieved with a metadataless filetree repo ... the metadata pertains to the ancestry of the package and if I'm not mistaken, both VA and VW ignore the ancestry data ...

**Comment by jbrichau** [comment]
That sound good for me @dalehenrich.

I also notice Pharo3 (at least) does not load metadata-less sources, even when I ask SmalltalkCI to load latest Metacello (https://travis-ci.org/SeasideSt/Seaside/jobs/256601070). Now, I would be in favour for dropping support for Pharo3 with Seaside 3.3 anyway... anybody feel otherwise?

**Comment by dalehenrich** [comment]
From the stack the error is occurring in **FileTree** .. It is very likely that metadataless support has not been back-ported to **FileTree** for Pharo3.0 ... IIRC the changes are not that big to add metadataless support, so metadataless support *could* be back-ported to Pharo3.0 FileTree ... but if you are not planning on supporting Seaside on Pharo3.3 anyway, the back-port can wait until another day:)

**Comment by marschall** [comment]
I would be fine with dropping Pharo 3 support in Seaside 3.3

**Comment by theseion** [comment]
+1
